### ISSUE TITLE
CW2

### ISSUE THREAD

**Issue by idSynth** [oleksandrblazhko/ai-212-ivanov#16]
# Завдання 1

## Потреба: чистота повітря навколишнього середовища

- FR1.1 - "Користувач обирає послугу для online-заявки"

Змінимо вимогу так, щоб вона перестала відповідати умові "атомарність":
“Користувач обирає послугу для online-заявки та вводить свої контактні дані”

- FR2.1 - "Користувач обирає метод оплати"

Змінимо вимогу так, щоб вона перестала відповідати умові "завершеність":
"Користувач обирає метод"

- FR2.2 - "Користувач вносить потрібну інформацію"

Змінимо вимогу так, щоб вона перестала відповідати умові "безкоштовність реалізації":
“Користувач вносить потрібну інформацію та здійснює оплату за допомогою кредитної картки”

# Завдання 2

1. Розподілена система (STi = 3): Цей показник відображає, що розподіленість системи має помірний вплив на технічну складність проекту. Хоча розподіленість є важливим аспектом, особливо для великих систем, що вимагають високої доступності та масштабованості, вона не є єдиним фактором, який визначає технічну складність.

2. Спеціальні вимоги до навчання користувачів (STi = 3): Цей показник відображає, що потреба в спеціалізованому навчанні користувачів має помірний вплив на технічну складність проекту. Хоча навчання користувачів є важливим аспектом для ефективного використання продукту, воно не є єдиним фактором, який визначає технічну складність.

# Завдання 3

## Користувач -- Онлайн-заявка

Один екземпляр об’єкту класу «Користувач» може мати декілька екземплярів об’єктів класу
«Онлайн-заявка».

FR 1.5 - Після завершення реєстрації заявки, користувач отримує оформлений зміст цієї заявки

## Користувач -- Метеорологічна послуга

Один екземпляр об’єкту класу «Користувач» може мати декілька екземплярів об’єктів класу
«Метеорологічна послуга».

FR 1.1 - Користувач обирає послугу для online-заявки

# Завдання 4

## Обгрунтування вибору моделі (MySQL): 

Основні переваги MySQL включають:

- Структурованість: MySQL дозволяє створювати добре структуровані та нормалізовані схеми даних, що сприяє ефективному управлінню даними.

- Надійність та безпека: MySQL відомий своєю надійністю, забезпечуючи різні рівні безпеки для захисту даних.

- Широке використання: MySQL є однією з найпопулярніших RDBMS, що означає, що існує багато ресурсів та спільноти для підтримки.

## Виявлений недолік процесу проектування

Порівняно з нереляційними моделями даних, такими як JSON, проектування схеми в MySQL може бути більш складним і часомічним, особливо для великих та складних наборів даних. Нереляційні моделі даних, такі як JSON, зазвичай надають більшу гнучкість, оскільки вони не вимагають жорсткої структури та можуть легко змінюватися. Однак, ця гнучкість може призвести до неконсистентності даних та проблем зі швидкодією на великих наборах даних.

**Comment by oleksandrblazhko** [comment]
“Користувач вносить потрібну інформацію та здійснює оплату за допомогою кредитної картки” - рішення помилкове.

Оцінка  = 3 бали
